/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as OrderFailedRouteImport } from './routes/order-failed'
import { Route as OrderAcceptedRouteImport } from './routes/order-accepted'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppFavouritesRouteImport } from './routes/_app.favourites'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppCheckoutRouteImport } from './routes/_app.checkout'
import { Route as AppCartRouteImport } from './routes/_app.cart'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppProductIdRouteImport } from './routes/_app.product.$id'
import { Route as AppCategoryNameRouteImport } from './routes/_app.category.$name'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFailedRoute = OrderFailedRouteImport.update({
  id: '/order-failed',
  path: '/order-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderAcceptedRoute = OrderAcceptedRouteImport.update({
  id: '/order-accepted',
  path: '/order-accepted',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppFavouritesRoute = AppFavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoryNameRoute = AppCategoryNameRouteImport.update({
  id: '/category/$name',
  path: '/category/$name',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/order-accepted': typeof OrderAcceptedRoute
  '/order-failed': typeof OrderFailedRoute
  '/otp': typeof OtpRoute
  '/phone': typeof PhoneRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/explore': typeof AppExploreRoute
  '/favourites': typeof AppFavouritesRoute
  '/home': typeof AppHomeRoute
  '/orders': typeof AppOrdersRoute
  '/search': typeof AppSearchRoute
  '/category/$name': typeof AppCategoryNameRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/order-accepted': typeof OrderAcceptedRoute
  '/order-failed': typeof OrderFailedRoute
  '/otp': typeof OtpRoute
  '/phone': typeof PhoneRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/account': typeof AppAccountRoute
  '/cart': typeof AppCartRoute
  '/checkout': typeof AppCheckoutRoute
  '/explore': typeof AppExploreRoute
  '/favourites': typeof AppFavouritesRoute
  '/home': typeof AppHomeRoute
  '/orders': typeof AppOrdersRoute
  '/search': typeof AppSearchRoute
  '/category/$name': typeof AppCategoryNameRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/order-accepted': typeof OrderAcceptedRoute
  '/order-failed': typeof OrderFailedRoute
  '/otp': typeof OtpRoute
  '/phone': typeof PhoneRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/checkout': typeof AppCheckoutRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/favourites': typeof AppFavouritesRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/category/$name': typeof AppCategoryNameRoute
  '/_app/product/$id': typeof AppProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/location'
    | '/login'
    | '/onboarding'
    | '/order-accepted'
    | '/order-failed'
    | '/otp'
    | '/phone'
    | '/signin'
    | '/signup'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/favourites'
    | '/home'
    | '/orders'
    | '/search'
    | '/category/$name'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/location'
    | '/login'
    | '/onboarding'
    | '/order-accepted'
    | '/order-failed'
    | '/otp'
    | '/phone'
    | '/signin'
    | '/signup'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/explore'
    | '/favourites'
    | '/home'
    | '/orders'
    | '/search'
    | '/category/$name'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/location'
    | '/login'
    | '/onboarding'
    | '/order-accepted'
    | '/order-failed'
    | '/otp'
    | '/phone'
    | '/signin'
    | '/signup'
    | '/_app/account'
    | '/_app/cart'
    | '/_app/checkout'
    | '/_app/explore'
    | '/_app/favourites'
    | '/_app/home'
    | '/_app/orders'
    | '/_app/search'
    | '/_app/category/$name'
    | '/_app/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrderAcceptedRoute: typeof OrderAcceptedRoute
  OrderFailedRoute: typeof OrderFailedRoute
  OtpRoute: typeof OtpRoute
  PhoneRoute: typeof PhoneRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-failed': {
      id: '/order-failed'
      path: '/order-failed'
      fullPath: '/order-failed'
      preLoaderRoute: typeof OrderFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-accepted': {
      id: '/order-accepted'
      path: '/order-accepted'
      fullPath: '/order-accepted'
      preLoaderRoute: typeof OrderAcceptedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favourites': {
      id: '/_app/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof AppFavouritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout': {
      id: '/_app/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product/$id': {
      id: '/_app/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/category/$name': {
      id: '/_app/category/$name'
      path: '/category/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof AppCategoryNameRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFavouritesRoute: typeof AppFavouritesRoute
  AppHomeRoute: typeof AppHomeRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppSearchRoute: typeof AppSearchRoute
  AppCategoryNameRoute: typeof AppCategoryNameRoute
  AppProductIdRoute: typeof AppProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppExploreRoute: AppExploreRoute,
  AppFavouritesRoute: AppFavouritesRoute,
  AppHomeRoute: AppHomeRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppSearchRoute: AppSearchRoute,
  AppCategoryNameRoute: AppCategoryNameRoute,
  AppProductIdRoute: AppProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrderAcceptedRoute: OrderAcceptedRoute,
  OrderFailedRoute: OrderFailedRoute,
  OtpRoute: OtpRoute,
  PhoneRoute: PhoneRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
